In [36]:
###########################
# 라이브러리 사용
import tensorflow as tf
import pandas as pd
import efficientnet.tfkeras
from tensorflow.keras.models import load_model
 
###########################
# 1.과거의 데이터를 준비합니다.
#파일경로 = 'Royal-Demo.csv'
파일경로 = 'Royal-Demo - 데이터셋(전체).csv'
스쿼트 = pd.read_csv(파일경로)
print(스쿼트.head())

 
# 원핫인코딩
인코딩 = pd.get_dummies(스쿼트)
print(인코딩.head())

     Name   X_leftEye   Y_leftEye  X_rightEye  Y_rightEye   X_leftEar  \
0  squart  288.566748  514.311904  321.609419  513.148116  253.316619   
1  squart  278.674674  454.263874  322.540993  452.503548  260.697404   
2  squart  287.052160  454.617199  328.276136  452.121928  262.942236   
3  squart  294.565789  495.077007  334.571240  498.965691  261.575424   
4  squart  293.859043  522.248430  332.006718  518.148346  259.544741   

    Y_leftEar  X_rightEar  Y_rightEar  X_leftShoulder  ...  X_rightHip  \
0  511.256800  347.643110  521.338341      230.462756  ...  356.893566   
1  469.278887  351.446237  466.452512      219.777259  ...  381.991527   
2  468.308754  355.517898  466.626313      220.369960  ...  367.621010   
3  498.776128  361.392407  514.268550      223.864523  ...  360.753955   
4  508.937120  350.659305  517.846752      230.130820  ...  350.192415   

   Y_rightHip  X_leftKnee  Y_leftKnee  X_rightKnee  Y_rightKnee  X_leftAnkle  \
0  821.852302  141.686672  799.09039

In [41]:

# 종속변수, 독립변수

독립 = 인코딩[['X_leftEye', 'Y_leftEye', 'X_rightEye', 'Y_rightEye', 'X_leftEar', 'Y_leftEar',
          'X_rightEar', 'Y_rightEar', 'X_leftShoulder', 'Y_leftShoulder', 'X_rightShoulder', 'Y_rightShoulder',
          'X_leftElbow', 'Y_leftElbow', 'X_rightElbow', 'Y_rightElbow', 'X_leftWrist', 'Y_leftWrist',
          'X_rightWrist', 'Y_rightWrist', 'X_leftHip', 'Y_leftHip', 'X_rightHip', 'Y_rightHip',
          'X_leftKnee', 'Y_leftKnee', 'X_rightKnee', 'Y_rightKnee', 'X_leftAnkle', 'Y_leftAnkle',
          'X_rightAnkle', 'Y_rightAnkle']]
"""
독립 = 인코딩[['X_leftHip', 'Y_leftHip', 'X_rightHip', 'Y_rightHip',
          'X_leftKnee', 'Y_leftKnee', 'X_rightKnee', 'Y_rightKnee', 'X_leftAnkle', 'Y_leftAnkle',
          'X_rightAnkle', 'Y_rightAnkle']]
"""
종속 = 인코딩[['Name_squart', 'Name_lunge']]

print(독립.shape, 종속.shape)
 
###########################
# 2. 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[32])
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(H)
H = tf.keras.layers.Dense(8, activation="swish")(H)
#Y = tf.keras.layers.Dense(2, activation='sigmoid')(H)
Y = tf.keras.layers.Dense(2, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics=['accuracy'])
#model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')
#model.compile(loss='sparse_categorical_crossentropy', metrics=['accuracy'])
#model.compile(loss='sparse_categorical_crossentropy', metrics=['accuracy'], optimizer='adam')


(175, 32) (175, 2)


In [46]:
#import os
#os.environ["CUDA_VISIBLE_DEVICES"] = '1'
###########################
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=5000, verbose=0)
model.fit(독립, 종속, epochs=10)
#model.fit(독립, 종속, epochs=1000)
 


Train on 175 samples
Epoch 1/10
175/175 [==============================] - 0s 423us/sample - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 2/10
175/175 [==============================] - 0s 394us/sample - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 3/10
175/175 [==============================] - 0s 400us/sample - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 4/10
175/175 [==============================] - 0s 331us/sample - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 5/10
175/175 [==============================] - 0s 337us/sample - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 6/10
175/175 [==============================] - 0s 280us/sample - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 7/10
175/175 [==============================] - 0s 286us/sample - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 8/10
175/175 [==============================] - 0s 439us/sample - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 9/10
175/175 [==============================] - 0s 337us/sample - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 1

In [47]:
###########################
# 4. 모델을 이용합니다
# 맨 처음 데이터 5개
print(model.predict(독립[:5]))
print(종속[:5])
 
# 맨 마지막 데이터 5개
print(model.predict(독립[-5:]))
print(종속[-5:])
 
###########################
# weights & bias 출력
print(model.get_weights())

# 모델 구조 확인
model.summary()

[[1.0000000e+00 2.0494989e-20]
 [1.0000000e+00 2.4069803e-21]
 [1.0000000e+00 4.3619567e-20]
 [1.0000000e+00 2.6233187e-21]
 [1.0000000e+00 5.8986999e-20]]
   Name_squart  Name_lunge
0            1           0
1            1           0
2            1           0
3            1           0
4            1           0
[[6.4033984e-26 1.0000000e+00]
 [2.0063631e-22 1.0000000e+00]
 [2.6107178e-30 1.0000000e+00]
 [1.4109728e-24 1.0000000e+00]
 [1.2122429e-34 1.0000000e+00]]
     Name_squart  Name_lunge
170            0           1
171            0           1
172            0           1
173            0           1
174            0           1
[array([[-0.05434397,  0.10024109, -0.35474783,  0.22978137,  0.24817742,
         0.28898957, -0.06830822, -0.02236491],
       [-0.0543592 ,  0.10250953, -0.3777731 ,  0.16903633,  0.16035368,
        -0.29536757, -0.36221698,  0.11773598],
       [ 0.15225679,  0.14647292,  0.10329337, -0.06223026,  0.3574859 ,
        -0.24835284,  0.08101428, -0

In [49]:
print(model.predict([[288.5635811, 74.82641973, 314.1459066, 72.9942168, 270.3436408, 75.34045125, 333.5154304, 
                      72.95374503, 243.4890429, 121.8909948, 360.0054681, 119.7803482, 177.6663346, 200.6256222,
                      418.5502, 208.0143773, 259.1567715, 138.3556172, 349.1564702, 136.4615056, 261.7116357,
                      238.5042153, 343.8131733, 233.4297759, 203.5678728, 290.5114236, 420.040598, 305.9406675,
                      203.9014745, 406.2844182, 388.8865669, 415.3967903]]))
print(model.predict([[261.9114737, 77.47740577, 268.4722929, 75.86081443, 239.1491751, 81.8575839, 270.2166486,
                      84.70840006, 227.8606102, 124.0278861, 264.4652577, 125.8829044, 234.8779313, 178.5306056,
                      260.8033413, 184.5076685, 269.2185486, 204.6749779, 283.1661357, 212.6565909, 231.0569406,
                      228.8754814, 255.7385514, 215.9008687, 184.4560941, 314.3076353, 334.4409214, 230.8246895,
                      158.7542076, 311.7643157, 306.4813724, 316.2113622]]))
print(model.predict([[280.5004788, 533.3913524, 316.8550234, 531.0858364, 258.5614042, 521.964101, 344.2684757,
                      511.4606546, 215.4491174, 573.4411492, 390.6041687, 578.7214236, 162.7099343, 724.0775121,
                      436.8975625, 710.9953791, 232.877105, 697.8611953, 368.1504694, 696.4655444, 257.1045585,
                      730.9315865, 341.7491295, 731.5682811, 148.1206952, 810.2919825, 442.6535194, 805.2840474,
                      147.6836351, 969.9592798, 431.4266058, 961.5285917]]))

[[2.327214e-10 1.000000e+00]]
[[4.443516e-18 1.000000e+00]]
[[1.0000000e+00 1.4690645e-20]]


In [50]:
print(model.predict([[132.5504792, 155.4797955, 144.50116, 153.0770933, 117.2536866, 161.2822513, 149.2750637,
                      157.2026857, 96.13969309, 200.6744463, 181.0256621, 200.3462827, 67.1686133, 257.5085288,
                      202.6894657, 255.8989729, 122.4556681, 207.477738, 146.1696798, 218.7431456, 113.9873358,
                      313.7727509, 171.8163212, 310.6380126, 26.04919386, 326.1487242, 235.2595416, 329.4338818,
                      65.58767641, 417.7684972, 202.2992747, 413.0381775]]))
print(model.predict([[210.5421014, 151.4121815, 214.2203387, 153.8782015, 185.0118377, 152.2944475, 195.3141853,
                      155.1928099, 170.5474173, 193.8708944, 185.5578509, 199.0063447, 119.7999641, 231.4222756,
                      110.2817774, 361.1326238, 144.3293008, 271.6118101, 161.2765574, 270.6331145, 157.1554144,
                      296.3803144, 161.0652915, 297.3453384, 250.0025376, 299.1496467, 241.3997153, 299.3501551,
                      244.267602, 382.8384518, 241.8677908, 383.441701]]))

[[1.0000000e+00 4.3740404e-11]]
[[1.5514923e-10 1.0000000e+00]]


In [ ]:
### Royal-Demo.py ###

###########################
# 라이브러리 사용
import tensorflow as tf
import pandas as pd
import efficientnet.tfkeras
from tensorflow.keras.models import load_model
 
###########################
# 1.과거의 데이터를 준비합니다.
#파일경로 = 'Royal-Demo.csv'
파일경로 = 'Royal-Demo - 데이터셋(전체).csv'
스쿼트 = pd.read_csv(파일경로)
print(스쿼트.head())

# 원핫인코딩
인코딩 = pd.get_dummies(스쿼트)
print(인코딩.head())

# 종속변수, 독립변수

독립 = 인코딩[['X_leftEye', 'Y_leftEye', 'X_rightEye', 'Y_rightEye', 'X_leftEar', 'Y_leftEar',
          'X_rightEar', 'Y_rightEar', 'X_leftShoulder', 'Y_leftShoulder', 'X_rightShoulder', 'Y_rightShoulder',
          'X_leftElbow', 'Y_leftElbow', 'X_rightElbow', 'Y_rightElbow', 'X_leftWrist', 'Y_leftWrist',
          'X_rightWrist', 'Y_rightWrist', 'X_leftHip', 'Y_leftHip', 'X_rightHip', 'Y_rightHip',
          'X_leftKnee', 'Y_leftKnee', 'X_rightKnee', 'Y_rightKnee', 'X_leftAnkle', 'Y_leftAnkle',
          'X_rightAnkle', 'Y_rightAnkle']]
"""
독립 = 인코딩[['X_leftHip', 'Y_leftHip', 'X_rightHip', 'Y_rightHip',
          'X_leftKnee', 'Y_leftKnee', 'X_rightKnee', 'Y_rightKnee', 'X_leftAnkle', 'Y_leftAnkle',
          'X_rightAnkle', 'Y_rightAnkle']]
"""
종속 = 인코딩[['Name_squart', 'Name_lunge']]

print(독립.shape, 종속.shape)

###########################
# 2. 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[32])
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(H)
H = tf.keras.layers.Dense(8, activation="swish")(H)
#Y = tf.keras.layers.Dense(2, activation='sigmoid')(H)
Y = tf.keras.layers.Dense(2, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics=['accuracy'])

###########################
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

###########################
# 4. 모델을 이용합니다
# 맨 처음 데이터 5개
print(model.predict(독립[:5]))
print(종속[:5])
 
# 맨 마지막 데이터 5개
print(model.predict(독립[-5:]))
print(종속[-5:])
 
###########################
# weights & bias 출력
print(model.get_weights())

# 모델 구조 확인
model.summary()